import './globals.css';
import React from 'react';
import TopBar from '@/components/TopBar';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <TopBar />
        <div className="pt-16">
          {children}
        </div>
      </body>
    </html>
  );
}
